### PR TITLE
Updated test & build matrix to include Python 3.13

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Python 2.7 builds failing:

```
cibuildwheel: No build identifiers selected: BuildSelector('cp27-*' - 'pp*')
```

Maybe it's time to drop support?

**Comment by edgarrmondragon** [comment]
> Maybe it's time to drop support?

Thoughts @etrepum?

**Comment by etrepum** [comment]
I'd rather not, at least without a sizable refactor to remove all of the related 2.x support code and a major version bump.

**Comment by etrepum** [comment]
I'm traveling for the next week and probably won't have time to do any troubleshooting myself, but if you can manage to get this passing with 2.x I can merge sooner.

**Comment by etrepum** [comment]
It looks like it's only failing on macOS, I would be fine dropping that platform for py27 support. I believe there's already some logic to skip windows so we can do that for mac as well.

**Comment by edgarrmondragon** [comment]
> It looks like it's only failing on macOS, I would be fine dropping that platform for py27 support. I believe there's already some logic to skip windows so we can do that for mac as well.

6900b4bc61e16f149b601cde36db5e2c592765c2

**Review by etrepum — APPROVED** [review]

**Pull request merged**
