### PR TITLE
Fix #201: pyenv usage on OS X

### LINKED ISSUE #201: Latest cp27m version of simplejson on PyPi for OS X is 3.8.2
I'm not sure why... 3.13.2 is available for cp27mu, but not cp27m. Curiously the python3 wheels are all built for cp3*m.

I can't figure out what's causing the abi mismatch :/

### PR DESCRIPTION
**Pull request by riannucci**

### CODE REVIEW

**Comment by riannucci** [comment]
Argh, I don't understand why this is happening:

https://travis-ci.org/simplejson/simplejson/jobs/330181827#L417

It looks like travis has some ultra-sticky pyenv implementation? It insists on putting ~/.pyenv on PATH instead of ~/.pyenv-simplejson.

**Comment by etrepum** [comment]
Could be related to https://github.com/travis-ci/travis-ci/issues/8363

**Comment by riannucci** [comment]
Hm... maybe it would be better to switch to travis' native python version support, e.g. https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions ?

It looks like it works with matrix builds too: https://github.com/behave/behave-django/blob/master/.travis.yml

**Comment by etrepum** [comment]
Does it work correctly for OS X?

**Comment by riannucci** [comment]
I think so? Only one way to find out :). Unfortunately I'm out for a week-ish, so I won't be able to update this pull request until Feb 1st. I'll set a reminder to look at this again then.

**Comment by ushuz** [comment]
3.14.0 has cp27m osx wheel available on PyPI, so the problem is resolved now?
https://pypi.org/project/simplejson/3.14.0/#files

**Comment by riannucci** [comment]
Yes it looks like since 3.10.0 there are os x wheels which work! Thanks (and sorry I took so long to follow up)

**Comment by riannucci** [comment]
Er sorry... since 3.14.0: https://pypi.org/project/simplejson/3.14.0/, which is what @ushuz said :) I misread the package names.

**Pull request closed without merging**
