### PR TITLE
Adding a paramter 'emptystr' for class JSONEncoder, to convert all null value to empty string in output result.

### PR DESCRIPTION
**Pull request by zhangqunshi**
Give user a choice to convert null to empty string in the output json. For example:

```
>>> import json
>>> x = {'hello': None}
>>> json.dumps(x)
'{"hello": null}'
```
When the parameter 'emptystr' is True, then become:
```
>>> import json
>>> x = {'hello': None}
>>> json.dumps(x, emptystr=True)
'{"hello": ""}'
```

This is useful in Django for web application.
But still need to pass paramter emtystr to c_make_encoder, and change its implementation.

Thanks,
Kris

### CODE REVIEW

**Comment by etrepum** [comment]
How would you output null in a document with this option turned on? What is the use case for it? I'm unlikely to accept a PR that implements this functionality, it doesn't seem general-purpose enough. Nobody else has asked for this functionality in the more than 10 years that simplejson has been around.

**Comment by zhangqunshi** [comment]
I think the use case is in UI display, usually the UI don't display null value. The UI develper has to convert the null value to empty string.
Nobody asked for this functionality in 10+ years -->I guess they use python function to covert None to empty string, and then pass the python object into simplejson, but it will need extra "for loop", and reduce performance.

**Comment by etrepum** [comment]
It's perfectly reasonable to expect the UI to handle null values appropriately when there is the possibility of a missing value. A string, even if empty, would be a very unpleasant surprise if another type entirely is expected (such as an object or array).

**Comment by zhangqunshi** [comment]
ok, thanks your help.

**Pull request closed without merging**
